# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    volumes:
      - "./src/model/schema.sql:/docker-entrypoint-initdb.d/schema.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080